export const GET_POST_INFO = 'get_post_info'
export const RESET_POST_LIST = 'reset_post_list'
export const FETCH_POST_LIST = 'fetch_post_list'
export const RESET_POST_CONTENT = 'reset_post_content'
export const FETCH_POST_CONTENT = 'fetch_post_content'
export const SET_TAG_NAME = 'set_tag_name'
export const FETCH_TAG_POST_LIST = 'fetch_tag_post_list'
export const GET_CLASSIFY = 'get_classify'
